name: Run Tests

on:
  push:
    branches: [ develop, main, release ]
  pull_request:
    branches: [ develop, main, release ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install project in editable mode with dev dependencies from pyproject.toml
          pip install -e ".[dev]"

      - name: Run Flake8
        run: |
          flake8 src/topovision

      - name: Run MyPy
        run: |
          mypy src/topovision

      - name: Run Pytest
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: pytest src/topovision/tests/ --maxfail=1 --disable-warnings -q
